#!/bin/bash
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.6/4.6.1/qt-creator-opensource-src-4.6.1.tar.xz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.5/4.5.2/qt-creator-opensource-src-4.5.2.tar.xz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.4/4.4.1/qt-creator-opensource-src-4.4.1.tar.xz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.3/4.3.1/qt-creator-opensource-src-4.3.1.tar.xz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.2/4.2.2/qt-creator-opensource-src-4.2.2.tar.xz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.1/4.1.0/qt-creator-opensource-src-4.1.0.tar.xz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/4.0/4.0.3/qt-creator-opensource-src-4.0.3.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.6/3.6.1/qt-creator-opensource-src-3.6.1.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.5/3.5.1/qt-creator-opensource-src-3.5.1.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.4/3.4.2/qt-creator-opensource-src-3.4.2.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.3/3.3.2/qt-creator-opensource-src-3.3.2.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.2/3.2.2/qt-creator-opensource-src-3.2.2.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.1/3.1.2/qt-creator-opensource-src-3.1.2.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/3.0/3.0.1/qt-creator-opensource-src-3.0.1.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/2.8/2.8.1/qt-creator-2.8.1-src.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/2.7/2.7.2/qt-creator-2.7.2-src.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/2.6/2.6.2/qt-creator-2.6.2-src.tar.gz
wget -c http://mirrors.ustc.edu.cn/qtproject/official_releases/qtcreator/2.5/2.5.2/qt-creator-2.5.2-src.tar.gz
