#!/bin/bash
#sudo apt install sendemail
#sudo apt remove sendemail
SENDFILE=$PWD/tool-sh/cron.minit/git-pull.log
NAME=$PWD/tool-sh/name
PASS=$PWD/tool-sh/pass-a
PASSA=$PWD/tool-sh/.pass-a
for qqname in $(cat $NAME)
do
    echo ""
done
HOSTNAME=$qqname
HOSTEMAIL=$qqname@qq.com
TARGET=1364036694@qq.com
openssl enc -des-ede3-cbc -in $PASS -out $PASSA -d -k 123456
for pass in $(cat $PASSA)
do
    echo ""
done
rm -rf $PASSA
emailpassword=$pass

sendemail -s smtp.qq.com -f ${HOSTEMAIL} -t ${TARGET} -u $SENDFILE -o message-file=$SENDFILE -xu ${HOSTNAME} -xp ${emailpassword} -o tls=auto 

